### ISSUE TITLE
rospy node crashes on changed rate

### ISSUE THREAD

**Issue by tdenewiler** [tdenewiler/node_example#22]
The rospy talker node crashes when the rate parameter is set to anything other than `1` and running:

    roslaunch node_example node_example.launch

The error is:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/timer.py", line 221, in run
    r = Rate(1.0 / self._period.to_sec(), reset=self._reset)
ZeroDivisionError: float division by zero
```

This should be fixed.

**Comment by tdenewiler** [comment]
Fixed by #23.
